print("Welcome to Band Name Generator!\n")
city = input("What's the name of the city you grew up in?\n")
print(city)
pet_name = input("What's your pet's name?\n")
print(pet_name)
print(f"Your band name could be {city} {pet_name}")